AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Task Definition and Lambda trigger for semantic search ingestion

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC to run the ECS task in
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for ECS task networking
  BranchName:
    Type: String
    Description: Git branch to use for deployments
    Default: main

Resources:
  SemanticSearchTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: SemanticSearchTaskS3SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource:
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-input-${BranchName}"
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-input-${BranchName}/*"
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-output-${BranchName}"
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-output-${BranchName}/*"
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

  LambdaTriggerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaECSRunTaskPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RunTask
                  - ecs:DescribeTasks
                  - ecs:DescribeTaskDefinition
                  - iam:PassRole
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

  SemanticSearchTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub 'semantic-search-ingestion-task-${BranchName}'
      Cpu: '512'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt SemanticSearchTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt SemanticSearchTaskRole.Arn
      ContainerDefinitions:
        - Name: semantic-search-ingestion
          Image: !Join
            - ":"
            - - !ImportValue
                'Fn::Sub': warc-file-extractor-ecr-uri-${BranchName}
              - latest
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/semantic-search-ingestion
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: ecs
          Environment:
            - Name: OUTPUT_BUCKET
              Value: !Ref SemanticSearchOutputBucket
            - Name: INPUT_BUCKET
              Value: !Ref SemanticSearchInputBucket
            - Name: IS_LOCAL
              Value: "false"
            - Name: KINESIS_FIREHOSE_STREAM
              Value: !Ref SemanticSearchFirehose
            - Name: BATCH_FILE_MANIFEST
              Value: ""  # To be overridden by Lambda at runtime

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub 'semantic-search-ingestion-cluster-${BranchName}'
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

  LambdaTriggerTaskFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'semantic-search-trigger-task-${BranchName}'
      Handler: index.handler
      Role: !GetAtt LambdaTriggerExecutionRole.Arn
      Runtime: python3.12
      Timeout: 60
      Environment:
        Variables:
          CLUSTER: !Ref ECSCluster
          TASK_DEFINITION: !Ref SemanticSearchTaskDefinition
          SUBNETS: !Join [",", !Ref SubnetIds]
          VPC: !Ref VpcId
          BRANCH_NAME: !Ref BranchName
          INPUT_BUCKET: !Ref SemanticSearchInputBucket
      Code:
        ZipFile: |
          import os
          import boto3
          import json

          def handler(event, context):
              # Get manifest S3 key from event and concatenate with input bucket
              manifest_key = event.get('BATCH_FILE_MANIFEST', '')
              if not manifest_key:
                  raise ValueError('BATCH_FILE_MANIFEST must be provided in the event')
              input_bucket = os.environ['INPUT_BUCKET']
              manifest_s3_path = f"s3://{input_bucket}/{manifest_key}"

              ecs = boto3.client('ecs')
              response = ecs.run_task(
                  cluster=os.environ['CLUSTER'],
                  taskDefinition=os.environ['TASK_DEFINITION'],
                  launchType='FARGATE',
                  networkConfiguration={
                      'awsvpcConfiguration': {
                          'subnets': os.environ['SUBNETS'].split(','),
                          'assignPublicIp': 'ENABLED'
                      }
                  },
                  overrides={
                      'containerOverrides': [
                          {
                              'name': 'semantic-search-ingestion',
                              'environment': [
                                  {'name': 'BATCH_FILE_MANIFEST', 'value': manifest_key}
                              ]
                          }
                      ]
                  }
              )
              # Ensure JSON serializable response
              def default_serializer(obj):
                  if hasattr(obj, 'isoformat'):
                      return obj.isoformat()
                  return str(obj)
              return json.loads(json.dumps(response, default=default_serializer))

  KinesisFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FirehoseS3DeliveryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:PutObject
                Resource:
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-output-${BranchName}"
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-output-${BranchName}/*"
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                Resource: '*'
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

  SemanticSearchFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub 'semantic-search-ingestion-firehose-${BranchName}'
      DeliveryStreamType: DirectPut
      S3DestinationConfiguration:
        BucketARN: !GetAtt SemanticSearchOutputBucket.Arn
        Prefix: 'processed-data/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/'
        ErrorOutputPrefix: 'error-data/'
        BufferingHints:
          SizeInMBs: 5
          IntervalInSeconds: 60
        CompressionFormat: GZIP
        RoleARN: !GetAtt KinesisFirehoseRole.Arn
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

  SemanticSearchInputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'semantic-search-ingestion-input-${BranchName}'
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  SemanticSearchOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'semantic-search-ingestion-output-${BranchName}'
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  SemanticSearchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/semantic-search-ingestion
      RetentionInDays: 14

  SemanticSearchTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: SemanticSearchTaskS3SQSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource:
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-input-${BranchName}"
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-input-${BranchName}/*"
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-output-${BranchName}"
                  - !Sub "arn:aws:s3:::semantic-search-ingestion-output-${BranchName}/*"
              - Effect: Allow
                Action: 
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - "arn:aws:s3:::commoncrawl*"
                  - "arn:aws:s3:::commoncrawl*/*"
                  - "arn:aws:s3:::*"
              - Effect: Allow
                Action:
                  - "firehose:PutRecord"
                  - "firehose:PutRecordBatch"
                Resource:
                  - !GetAtt SemanticSearchFirehose.Arn
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

Outputs:
  TaskDefinitionArn:
    Description: ARN of the ECS Task Definition
    Value: !Ref SemanticSearchTaskDefinition
    Export:
      Name: !Sub "${AWS::StackName}-TaskDefinitionArn-${BranchName}"
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaTriggerTaskFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-LambdaFunctionArn-${BranchName}"
  SemanticSearchInputBucketName:
    Description: Name of the S3 input bucket
    Value: !Ref SemanticSearchInputBucket
    Export:
      Name: !Sub "${AWS::StackName}-SemanticSearchInputBucketName-${BranchName}"
  SemanticSearchOutputBucketName:
    Description: Name of the S3 output bucket
    Value: !Ref SemanticSearchOutputBucket
    Export:
      Name: !Sub "${AWS::StackName}-SemanticSearchOutputBucketName-${BranchName}"
  SemanticSearchFirehoseName:
    Description: Name of the Kinesis Firehose delivery stream
    Value: !Ref SemanticSearchFirehose
    Export:
      Name: !Sub "${AWS::StackName}-SemanticSearchFirehoseName-${BranchName}"
