version: 0.2

phases:
  install:
    commands:
      - echo "Installing prerequisites..."

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID".dkr.ecr."$REGION".amazonaws.com
      - REPOSITORY_URI="$AWS_ACCOUNT_ID".dkr.ecr."$REGION".amazonaws.com/"$ECR_REPOSITORY_NAME"
      - COMMIT_HASH=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."
      - echo "Current working directory: $(pwd)"
      - echo "Files in current directory:"
      - ls -la
      - echo "Building Docker image with tag: $IMAGE_TAG"