Parameters:
  BranchName:
    Type: String
    Description: Git branch to use for deployments
    Default: main

Resources:
  # AWSECRRepository:
  #   Type: AWS::ECR::Repository
  #   Properties:
  #     RepositoryName: !Sub 'assi-sagemaker-${BranchName}'
  #     ImageScanningConfiguration:
  #       scanOnPush: true
  #     Tags:
  #       - Key: Name
  #         Value: !Sub 'assi-sagemaker-${BranchName}'
  #       - Key: project
  #         Value: aws-semantic-search-ingestion
  SageMakerModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'assi-sagemaker-model-${BranchName}'
      Tags:
        - Key: Name
          Value: !Sub 'assi-sagemaker-model-${BranchName}'
        - Key: project
          Value: aws-semantic-search-ingestion

  SageMakerOutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'assi-sagemaker-output-${BranchName}'
      Tags:
        - Key: Name
          Value: !Sub 'assi-sagemaker-output-${BranchName}'
        - Key: project
          Value: aws-semantic-search-ingestion

Outputs:
  # ECRRepositoryArn:
  #   Description: ARN of the ECR repository
  #   Value: !GetAtt AWSECRRepository.Arn
  #   Export:
  #     Name: !Sub 'assi-sagemaker-ecr-arn-${BranchName}'
  # ECRRepositoryUri:
  #   Description: URI of the ECR repository
  #   Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/assi-sagemaker-${BranchName}"
  #   Export:
  #     Name: !Sub 'assi-sagemaker-ecr-uri-${BranchName}'
  SageMakerModelBucketName:
    Description: Name of the S3 bucket for SageMaker models
    Value: !Ref SageMakerModelBucket
    Export:
      Name: !Sub 'assi-sagemaker-model-bucket-name-${BranchName}'
  SageMakerModelBucketArn:
    Description: ARN of the S3 bucket for SageMaker models
    Value: !GetAtt SageMakerModelBucket.Arn
    Export:
      Name: !Sub 'assi-sagemaker-model-bucket-arn-${BranchName}'
  SageMakerOutputBucketName:
    Description: Name of the S3 bucket for SageMaker output
    Value: !Ref SageMakerOutputBucket
    Export:
      Name: !Sub 'assi-sagemaker-output-bucket-name-${BranchName}'
  SageMakerOutputBucketArn:
    Description: ARN of the S3 bucket for SageMaker output
    Value: !GetAtt SageMakerOutputBucket.Arn
    Export:
      Name: !Sub 'assi-sagemaker-output-bucket-arn-${BranchName}'