services:
  sagemaker-inference:
    image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.13.1-transformers4.26.0-cpu-py39-ubuntu20.04
    env_file:
      - .env
    volumes:
      - ./models:/opt/ml/model
      - ./inference.py:/opt/ml/model/inference.py
      - ./input:/opt/ml/processing/input
      - ./output:/opt/ml/processing/output
    command: []