AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD Pipeline for Semantic Search Ingestion

Parameters:
  ConnectionArn:
    Type: String
    Description: ARN of the CodeStar Connection to GitHub
  GitHubUser:
    Type: String
    Description: GitHub username or organization
  GitHubRepo:
    Type: String
    Description: GitHub repository name
  BranchName:
    Type: String
    Description: Git branch to use for deployments
    Default: main
  AWSAccountId:
    Type: String
    Description: AWS Account ID for ECR and CodeBuild

Resources:
  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'assi-artifacts-${BranchName}'
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - codebuild:*
                  - iam:PassRole
                Resource: '*'
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:*
                  - logs:*
                  - s3:*
                  - lambda:*
                  - cloudformation:*
                  - iam:PassRole
                Resource: '*'
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

  DockerBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: DockerBuildProject
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWSAccountId
          - Name: BRANCH_NAME
            Value: !Ref BranchName
      Source:
        Type: CODEPIPELINE
        BuildSpec: 1_fargate_task/buildspec.yml
      TimeoutInMinutes: 30
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub 'assi-code-pipeline-${BranchName}'
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Sub "${GitHubUser}/${GitHubRepo}"
                BranchName: !Ref BranchName
                DetectChanges: true
        - Name: BuildDocker
          Actions:
            - Name: BuildDocker
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: DockerBuildOutput
              Configuration:
                ProjectName: !Ref DockerBuildProject
      Tags:
        - Key: project
          Value: aws-semantic-search-ingestion